/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hostchat.clientinterface;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 5b08
 */
public class Client extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Client
     */
    private Socket connection = null;
    private String server = "localHost";
    private int port = 24680;
		
    private InputStreamReader in;
    private BufferedReader sIN;
    private OutputStream out;
    private PrintWriter sOut;
    
    String mex;
    
    String otherHostName;
		
    private InputStreamReader input;
    private BufferedReader tastiera;
		
    private String name, pass;
		
    private int accept = 0;

    /**
     * Creates new form NumberAdditionUI
     */
    public Client() {
        initComponents();
        loginError.setVisible(false);
        signupError.setVisible(false);
        Log.setVisible(true);
        /*loginLx.setVisible(true);
        loginRx.setVisible(true);*/
        
        chatPanel.setVisible(false);
        //errorLabel3.setVisible(false);
        
        
        /*if(Server.instance == null){
            Server server = new Server();
            Server.instance = server;
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatPanel = new javax.swing.JPanel();
        log = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        onlineList = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        chat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        inputText = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        Log = new javax.swing.JPanel();
        loginRx = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        serverField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        loginError = new javax.swing.JLabel();
        signupError = new javax.swing.JLabel();
        loginLx = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        chatPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        log.setBackground(new java.awt.Color(211, 140, 30));
        log.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportBorder(new javax.swing.border.MatteBorder(null));

        onlineList.setEditable(false);
        onlineList.setBackground(new java.awt.Color(135, 113, 79));
        onlineList.setColumns(20);
        onlineList.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        onlineList.setForeground(new java.awt.Color(77, 142, 44));
        onlineList.setLineWrap(true);
        onlineList.setRows(5);
        onlineList.setBorder(null);
        jScrollPane2.setViewportView(onlineList);

        log.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 390));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("ONLINE:");
        log.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jButton3.setBackground(new java.awt.Color(158, 119, 75));
        jButton3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        log.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 110, 30));

        chatPanel.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 530));

        chat.setBackground(new java.awt.Color(19, 168, 173));
        chat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chatArea.setEditable(false);
        chatArea.setBackground(new java.awt.Color(249, 249, 249));
        chatArea.setColumns(20);
        chatArea.setForeground(new java.awt.Color(51, 51, 51));
        chatArea.setRows(5);
        chatArea.setBorder(null);
        jScrollPane1.setViewportView(chatArea);

        chat.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 470, 410));

        inputText.setBackground(new java.awt.Color(19, 168, 173));
        inputText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputText.setForeground(new java.awt.Color(255, 255, 255));
        inputText.setText("Insert a message");
        inputText.setBorder(null);
        inputText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputTextMouseClicked(evt);
            }
        });
        inputText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputTextKeyPressed(evt);
            }
        });
        chat.add(inputText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 380, 20));
        chat.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 360, 10));

        jButton4.setBackground(chat.getBackground());
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        chat.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 50, 40));

        chatPanel.add(chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 530, 530));

        Log.setPreferredSize(new java.awt.Dimension(715, 532));
        Log.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginRx.setBackground(new java.awt.Color(102, 102, 102));
        loginRx.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("SIGNUP OR LOGIN");
        loginRx.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("IP SERVER");
        loginRx.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("USERNAME");
        loginRx.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("PASSWORD");
        loginRx.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        loginRx.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 200, 20));
        loginRx.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 200, 20));
        loginRx.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 200, 20));

        serverField.setBackground(loginRx.getBackground());
        serverField.setForeground(new java.awt.Color(255, 255, 255));
        serverField.setText("192.168.104.119");
        serverField.setToolTipText("");
        serverField.setBorder(null);
        serverField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serverFieldMouseClicked(evt);
            }
        });
        serverField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverFieldActionPerformed(evt);
            }
        });
        loginRx.add(serverField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 200, -1));

        nameField.setBackground(loginRx.getBackground());
        nameField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        nameField.setForeground(new java.awt.Color(255, 255, 255));
        nameField.setText("USERNAME");
        nameField.setToolTipText("");
        nameField.setBorder(null);
        nameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameFieldMouseClicked(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        loginRx.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 200, -1));

        passField.setBackground(loginRx.getBackground());
        passField.setText("jPasswordField1");
        passField.setBorder(null);
        passField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passFieldMouseClicked(evt);
            }
        });
        loginRx.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 200, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("LOGIN");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginRx.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 120, 40));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setText("SIGNUP");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        loginRx.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 120, 40));

        loginError.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        loginError.setForeground(new java.awt.Color(255, 0, 0));
        loginError.setText("USERNAME OR PASSWORD WRONG");
        loginRx.add(loginError, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        signupError.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        signupError.setForeground(new java.awt.Color(255, 0, 0));
        signupError.setText("USERNAME IS ALREADY TAKEN");
        loginRx.add(signupError, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        Log.add(loginRx, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, 440, 530));

        loginLx.setBackground(new java.awt.Color(0, 153, 153));
        loginLx.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setText("CHAT");
        loginLx.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        loginLx.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        Log.add(loginLx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 532));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(chatPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Log, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(chatPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Log, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serverFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serverFieldMouseClicked
        // TODO add your handling code here:
        serverField.setText("");
    }//GEN-LAST:event_serverFieldMouseClicked

    private void nameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameFieldMouseClicked
        // TODO add your handling code here:
        nameField.setText("");
    }//GEN-LAST:event_nameFieldMouseClicked

    private void passFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passFieldMouseClicked
        // TODO add your handling code here:
        passField.setText("");
    }//GEN-LAST:event_passFieldMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean clientData = false;
        boolean serverData = false;
        
        //CONTROLLO CREDENZIALI CLIENT
        if(!nameField.getText().equals("") && !passField.getText().equals("")){
            clientData = true;
            loginError.setVisible(false);
        }else{
            loginError.setVisible(true);
        }
        
        
        //CONTROLLO CREDENZIALI SERVER
        if(!serverField.getText().equals("")){
            serverData = true;
            loginError.setVisible(false);
        }else{
            loginError.setVisible(true);
        }
        
        //CONTROLLO PORTA
        /*if(checkNumber(portField.getText())){
            portNumber = true;
            errorLabel3.setVisible(false);
        }else{
            errorLabel3.setVisible(true);
        }*/
        
        if(clientData && serverData){
            name = nameField.getText();
            pass = passField.getText();
            
            try {
                connection = new Socket(server, port);

                out = connection.getOutputStream();
                sOut = new PrintWriter(out);
                in = new InputStreamReader(connection.getInputStream());
                sIN = new BufferedReader(in);

                sOut.println("CONFIRM");
                sOut.flush();
                sOut.println(0+";"+name+";"+pass);
                sOut.flush();	
                accept = Integer.parseInt(sIN.readLine());
            } catch (UnknownHostException e) {
                System.out.println("Connection Error");;
            } catch (IOException e) {
                e.printStackTrace();
            }
            if(accept==1){
                new Thread(this).start();
                Log.setVisible(false);
                /*loginLx.setVisible(false);
                loginRx.setVisible(false);*/
                chatPanel.setVisible(true);
                
            }else if (accept==0){
                loginError.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean clientData = false;
        boolean serverData = false;
        
        //CONTROLLO CREDENZIALI CLIENT
        if(!nameField.getText().equals("") && !passField.getText().equals("")){
            clientData = true;
            signupError.setVisible(false);
        }else{
            signupError.setVisible(true);
        }
        
        
        //CONTROLLO CREDENZIALI SERVER
        if(!serverField.getText().equals("")){
            serverData = true;
            signupError.setVisible(false);
            server = serverField.getText();
        }else{
            signupError.setVisible(true);
        }
        
        //CONTROLLO PORTA
        /*if(checkNumber(portField.getText())){
            portNumber = true;
            errorLabel3.setVisible(false);
        }else{
            errorLabel3.setVisible(true);
        }*/
        
        if(clientData && serverData){
            name = nameField.getText();
            pass = passField.getText();
            System.out.println(name+"  " + pass);
            
            try {
                System.out.println("connecting to the server...");
                connection = new Socket(server, port);
                System.out.println("connected to server");
                out = connection.getOutputStream();
                sOut = new PrintWriter(out);
                in = new InputStreamReader(connection.getInputStream());
                sIN = new BufferedReader(in);
                
                sOut.println("CONFIRM");
                sOut.flush();
                System.out.println("serevr confirm send");
                sOut.println(1+";"+name+";"+pass);
                System.out.println(1+";"+name+";"+pass);
                sOut.flush();	
                accept = Integer.parseInt(sIN.readLine());
            } catch (UnknownHostException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
            
            if(accept == 1){
                new Thread(this).start();
                Log.setVisible(false);
                /*loginLx.setVisible(false);
                loginRx.setVisible(false);*/
                chatPanel.setVisible(true);
            }else{
                signupError.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void inputTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputTextMouseClicked
        // TODO add your handling code here:
        inputText.setText("");
    }//GEN-LAST:event_inputTextMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        sOut.println("END_CONNECTION");
        sOut.flush();
        signupError.setVisible(false);
        loginError.setVisible(false);
        chatArea.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(!inputText.getText().equals("")){
            sOut.println(inputText.getText());
            sOut.flush();
            inputText.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        sOut.println("END_CONNECTION");
        sOut.flush();
        String confirm;
        try{
            while(true){
                confirm = sIN.readLine();
                if(confirm.equals("END_CONNECTION_CONFIRM")) break;
            }
            connection.close();
        }catch(IOException e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_formWindowClosing

    private void inputTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextKeyPressed
        // TODO add your handling code here:
        if(inputText.getText().contains("\n")){
            if(!inputText.getText().equals("")){
                sOut.println(inputText.getText());
                sOut.flush();
                inputText.setText("");
            }
        }
    }//GEN-LAST:event_inputTextKeyPressed

    private void serverFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverFieldActionPerformed

    
     private boolean checkNumber(String text){
        for(int i = 0; i < text.length(); i++){
            if(text.charAt(i) < 48 || text.charAt(i) > 57){
                return false;
            }
        }
        return true;
    }
    
    public void run() {
        StringTokenizer st;
        String current;
        try {
            while(true){
                try {
                    mex = sIN.readLine();
                    if(mex.equals("END_CONNECTION_CONFIRM")){
                        chatPanel.setVisible(false);
                        Log.setVisible(true);
                        /*loginLx.setVisible(true);
                        loginRx.setVisible(true);*/
                        break;
                    }
                    switch(mex.substring(0, 3)){
                        case "/1:":
                            chatArea.append(mex.substring(3)+"\n");
                            st = new StringTokenizer(mex.substring(3), " ");
                            current = st.nextToken();
                            if(current.equals(name)) continue;
                            onlineList.append(current + "\n");
                        break;
                        
                        case "/2:":
                            onlineList.setText("");
                            st = new StringTokenizer(mex.substring(3), ";");
                            for(int i = 0; st.hasMoreTokens(); i++){
                                current = st.nextToken();
                                if(current.equals(name)) continue;
                                onlineList.append(current + "\n");
                            }
                        break;
                        
                        default:
                            chatArea.append(mex+"\n");
                            
                    }   
                    
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            accept = 0;
            connection.close();
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Log;
    private javax.swing.JPanel chat;
    private javax.swing.JTextArea chatArea;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JTextField inputText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel log;
    private javax.swing.JLabel loginError;
    private javax.swing.JPanel loginLx;
    private javax.swing.JPanel loginRx;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextArea onlineList;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField serverField;
    private javax.swing.JLabel signupError;
    // End of variables declaration//GEN-END:variables
}
